<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-IQISSAG" ignored="0" name="Test" tests="7" failures="1" timestamp="2019-12-27T16:32:05 IST" time="6.076" errors="0">
  <testcase name="checkResponseBody" time="0.022" classname="com.employeecheck.testcases.TC001_GetAllEmployees"/>
  <testcase name="checkResponseTime" time="0.001" classname="com.employeecheck.testcases.TC001_GetAllEmployees"/>
  <testcase name="checkServerType" time="0.001" classname="com.employeecheck.testcases.TC001_GetAllEmployees"/>
  <testcase name="checkStatusCode" time="0.001" classname="com.employeecheck.testcases.TC001_GetAllEmployees"/>
  <testcase name="checkResponseBody" time="0.256" classname="com.employeecheck.testcases.TC003_PostEmployeeRecord"/>
  <testcase name="checkStatusCode" time="0.002" classname="com.employeecheck.testcases.TC003_PostEmployeeRecord"/>
  <testcase name="checkDeleteReponse" time="0.002" classname="com.employeecheck.testcases.TC004_DeleteEmployeeRecord">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.assertTrue(Assert.java:43)
at org.junit.Assert.assertTrue(Assert.java:54)
at com.employeecheck.testcases.TC004_DeleteEmployeeRecord.checkDeleteReponse(TC004_DeleteEmployeeRecord.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkDeleteReponse -->
</testsuite> <!-- Test -->
